### ISSUE TITLE
NO-Ip Problem

### ISSUE THREAD

**Issue by ghost** [pasahitz/zirikatu#1]
first ,thanks for this script, but when i chose reverse_tcp_dns payload  , i can't put my dns no-ip in lhost ,it's told me invalid ip !!! fix it please

**Comment by pasahitz** [comment]
Soon the next version. Fix dns_payload problem. Thank you for your comment

**Comment by ghost** [comment]
ok thanks man keep up

**Comment by pasahitz** [comment]
A new version(0.2) available fix this problem
