### ISSUE TITLE
problem with avast!

### ISSUE THREAD

**Issue by gearcapitan** [pasahitz/zirikatu#2]
Hello, I have a problem with avast, and its sanbox, in what the antivirus analyzes the file the session of meterpreter is closed, but since the executable is not detected as such, if not only by procedure avast parses The files in sanbox mode by default, when it finishes re-executing the file but the problem is just a simple code in the script so that this is not a problem, what I did was add in the handler this line

echo "set EXITONSESSION false" >> $dir/handler/handler.rc

And ready with that is all full: D

**Comment by pasahitz** [comment]
Gearcapitan, thanks for your comment. Your advise is better if a closed meterpreter connection occurs avast sanbox is a example. I add echo "set EXITONSESSION false" >> $dir/handler/handler.rc
and deleted duplicate code.
