### ISSUE TITLE
Multiplataforma

### ISSUE THREAD

**Issue by wuilmerbolivar** [pasahitz/zirikatu#3]
No permite crear payloads para plataformas como:
Windows
Android
Linux
o Mac.

**Comment by pasahitz** [comment]
Este script esta creado para windows aunque la informacion brille por su ausencia. No lo voy a desarrollar para otras plataformas. Cierro esta incidencia y dejo la puerta abierta al que quiera desarrolar este programa.
Saludos y gracias por tu comentario
