### ISSUE TITLE
how to set no-ip as LHOST

### ISSUE THREAD

**Issue by praveenyadav1602** [pasahitz/zirikatu#4]
i had select payload number 4(payload='windows/meterpreter/reverse_tcp_dns') 
it ask for  Set Your No-Ip Hostname> ok i had set my no-ip hostname

after that it ask for set LHOST.
why i  need to set LHOST when we already set no-ip?
and what ip i set as LHOST?

**Comment by pasahitz** [comment]
Check this
https://www.youtube.com/watch?v=UYtObW8-R0c

**Comment by praveenyadav1602** [comment]
thanks. bro
