### ISSUE TITLE
A local variable named `HexadezimalKatea' is already defined in this scope

### ISSUE THREAD

**Issue by anthaeus** [pasahitz/zirikatu#5]
Hi,

the script is pretty usefull, however I am encountering error on gentoo

"Please wait a few seconds..........
â║║║║║║║║║║
Kodea(19,8): error CS0128: A local variable named `HexadezimalKatea' is already defined in this scope
Compilation failed: 1 error(s), 0 warnings
stat: cannot stat '<PATH HERE>/zirikatu/output/a.exe': No such file or directory

Succesfully Payload generated !!

Payload file= /home/ant_/h4/tools/new/zirikatu/output/a.exe
Payload size= 1483 Bytes"

after failing there is no exception handling so scipt exits with 'no error' message which is totally wrong.

any ideas on the Kodea error?

**Comment by pasahitz** [comment]
You must update metasploit framework
